default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: notifier
  username: rsp
  password: rsp
  host: localhost
  port: 5432
development:
  <<: *default
  database: notifier_dev
test:
  <<: *default
  database: notifier_test

production:
  <<: *default
  database: notifier_prod
